#!/usr/bin/php
<?php

// Load the test config and script
$sTestData   = $argv[1];
$sTestScript = $argv[2];

if(!file_exists($sTestData)) {
    die("No test data: $sTestData\n");
}

if(!file_exists($sTestScript)) {
    die("Bogus test script: $sTestScript\n");
}

exec("php -l $sTestData", $output, $iReturnVar);
if($iReturnVar != 0) {
    echo "Can't parse test data $sTestData\n";
    exit(1);
}

exec("php -l $sTestScript", $output, $iReturnVar);
if($iReturnVar != 0) {
    echo "Can't parse test script $sTestScript\n";
    exit(1);
}

$aTests = require $sTestData;

if(!is_array($aTests)) {
    echo 'Invalid test config (must be an array with keys "type" and "cases")' . "\n";
    exit(1);
}

if(!isset($aTests['type'])) {
    echo "Unknown test type\n";
    exit(1);
}

if(!isset($aTests['cases'])) {
    echo "Found no test cases\n";
    exit(1);
}

$sName = '';
if(isset($aTests['name'])) {
    $sName = $aTests['name'];
}

$sTestType = $aTests['type'];
require './src/OutputHelper.php';
require './src/TestRunner.php';
require "./src/{$sTestType}.php";
$oTester = new $sTestType($sName);

try {
    $oTester->loadConfig($aTests['cases']);
    $oTester->displayTestBanner();
} catch(Exception $e) {
    echo "$sTestScript\n";
    exit(1);
}

// TEST HARNESS
while($oTester->hasMoreCases()) {
    $oTester->loadTest($sTestScript);
    $oTester->run();
}

$oTester->displayResults();
